Revert "uprobes/x86: Fix detection of 32-bit user mode"
This reverts commit 3c770f81470780c72e0a824ce996b95ed6bbaea7 which is
9212ec7d8357ea630031e89d0d399c761421c83b upstream.

A mail from Intel's 0-day reports:

tree:   https://android.googlesource.com/kernel/common android-3.18
head:   3c770f81470780c72e0a824ce996b95ed6bbaea7
commit: 3c770f81470780c72e0a824ce996b95ed6bbaea7 [139/139] uprobes/x86: Fix detection of 32-bit user mode
config: i386-allyesconfig (attached as .config)
compiler: gcc-5 (Ubuntu 5.5.0-12ubuntu1) 5.5.0 20171010
reproduce:
        git checkout 3c770f81470780c72e0a824ce996b95ed6bbaea7
        # save the attached .config to linux build tree
        make ARCH=i386

If you fix the issue, kindly add following tag
Reported-by: kbuild test robot <lkp@intel.com>

All errors (new ones prefixed by >>):

   arch/x86//kernel/uprobes.c: In function 'sizeof_long':
>> arch/x86//kernel/uprobes.c:463:9: error: implicit declaration of function 'user_64bit_mode' [-Werror=implicit-function-declaration]
     return user_64bit_mode(regs) ? 8 : 4;
            ^
   cc1: some warnings being treated as errors

vim +/user_64bit_mode +463 arch/x86//kernel/uprobes.c

   457
   458  static inline int sizeof_long(struct pt_regs *regs)
   459  {
   460          /*
   461           * Check registers for mode as in_xxx_syscall() does not apply here.
   462           */
 > 463          return user_64bit_mode(regs) ? 8 : 4;
   464  }
   465

Reported-by: kbuild test robot <lkp@intel.com>
Signed-off-by: Lee Jones <lee.jones@linaro.org>
Change-Id: Ib65a81df3ac27bf4b165d6e956fa0d4608ce7ec8