Revert "tty/serial: atmel: fix TX path in atmel_console_write()"
This reverts commit edf033a3115c2dd843eba163ffb9619fd5c59852.

Fixes the following build error:

 drivers/tty/serial/atmel_serial.c: In function ‘atmel_console_write’:
 drivers/tty/serial/atmel_serial.c:2310:2: error: implicit declaration of function ‘atmel_uart_writel’; did you mean ‘atmel_start_tx’? [-Werror=implicit-function-declaration]
  atmel_uart_writel(port, ATMEL_US_CR, ATMEL_US_TXEN);
  ^~~~~~~~~~~~~~~~~

It wasn't caught earlier because it only affects at91* defconfigs.

Signed-off-by: Lee Jones <lee.jones@linaro.org>
Change-Id: I6ef1114525d3c1acf5afdb26fdbff5e36e9fc8e1